//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrupoSatelitePruebaTecnica.DataContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class MateriasxGrado
    {
        public int IdMxG { get; set; }
        public int IdGrado { get; set; }
        public int IdMateria { get; set; }
    
        public virtual Grado Grado { get; set; }
        public virtual Materia Materia { get; set; }
    }
}
